name: test
description: osint
author: bbo
version: "0.1"
stages: 
  inputName: 
    plugin: rawinput
    config: 
      data: "bouachour.benjamin@gmail.com"
  holehe:
    parents: 
      - inputName
    plugin: docker
    pipe: 
      - goTemplate:
          format: string
          pattern: "holehe --only-used --no-color --no-clear {{ . }}"
    config:
      host: unix:///Users/benjamin/.orbstack/run/docker.sock
      image: "holehe:latest"
  transformResult: 
    parents: 
      - holehe
    plugin: forward
    pipe: 
      - split:
          sep: "\n"
      - goTemplate: 
          pattern: "{{ trim . }}"
          format: string
      - regex:
          pattern: '^\[\+\](.*\..*)$'
          select: 1
      - goTemplate: 
          format: string
          pattern: "https://{{ trim  . }}"
