name: test
description: osint
author: bbo
version: "0.1"
stages: 
  inputName: 
    plugin: rawinput
    config: 
      data: "benjamin.bouachour@gmail.com"
  holehe:
    parents: 
      - inputName
    plugin: docker
    pipe: 
      - goTemplate:
          format: string
          pattern: "holehe --only-used {{ . }}"
    config:
    
      image: "holehe:latest"
  output: 
    plugin: output
    parents: 
      - holehe
    

        