name: test
description: osint
author: bbo
version: "0.1"
stages: 
  inputName: 
    plugin: rawinput
    config: 
      data: "benjamin.bouachour@gmail.com"
  holehe:
    parents: 
      - inputName
    plugin: docker
    pipe: 
      - goTemplate:
          format: string
          pattern: "holehe  {{ . }}"
    config:
      host: unix:///Users/benjamin/.orbstack/run/docker.sock
      image: "holehe:latest"


        